config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'
  get 'calendar', to: 'pages#calendar'
  get 'club_events', to: 'pages#club_events'
  get 'trainings', to: 'pages#trainings'
  get 'contests', to: 'pages#contests'
  get 'school', to: 'pages#school'
  get 'results', to: 'pages#results'
  get 'my_articles', to: 'pages#my_articles'
  get 'my_ads', to: 'pages#my_ads'
  get 'triathlon2023', to: 'pages#triathlon2023'
  get 'forum_sports', to:'pages#forum_sports'
  get 'divers', to: 'pages#divers'
  get 'subscription', to: 'pages#subscription'

  get 'sportswears', to: 'products#sportswears'
  get 'petites_annonces', to: 'products#petites_annonces'

  get 'finances', to: 'clubs#finances'
  get 'impots', to: 'clubs#impots'
  get 'la_division_3', to: 'd3_contests#division_3'

  # Google API test
  get '/redirect', to: 'calendar#redirect', as: 'redirect'
  get '/callback', to: 'calendar#callback', as: 'callback'
  get '/calendars', to: 'calendar#calendars', as: 'calendars'
  get '/events', to: 'calendar#events', as: 'events'



  resources :pictures, only: [:index, :new, :create, :show, :edit, :update]
  #TODO create update method

  resources :users
  resources :dashboards, only: [:index]
  resources :articles do
    resources :reviews, only: [:new, :create]
    resources :likes, only: [:new, :create, :update]
    resources :participations, only: [:new, :create, :destroy]
  end
  resources :products, only: [:new, :show, :create, :edit, :update, :destroy]
  resources :clubs, only: [:index, :new, :edit, :show, :create, :update]
  resources :tests, only: [:index, :new, :create]
  resources :notifications, only: [:index, :edit, :update]
  resources :newsletters, only: [:index, :edit, :update]

  resources :d3_contests
  resources :d3_results
  resources :partners
  resources :workouts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.member } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/article.rb
class Article < ApplicationRecord
  # belongs_to :user
  belongs_to :article_type
  has_many :reviews
  has_many :likes
  has_many :participations
  has_many :authors
  mount_uploader :photo, PhotoUploader

  validates :name, presence: true, length: {maximum: 60, minimum: 5}
  validates :date, presence: true
  validates :article_type_id, presence: true
  validates :photo, presence: true
  validates :location, presence: true, length: {maximum: 60, minimum: 5}


  def total_likes
    sum = 0
    self.likes.each do |like|
      sum += like.like
    end
    return sum
  end

  def count_reviews
    sum = 0
    self.reviews.each do |review|
      if !review.content.nil?
        sum += 1
      end
    end
    return sum
  end

  def notification?
    !Notification.where(article_id: self.id).empty?
  end
end

app/models/author.rb
class Author < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/club.rb
class Club < ApplicationRecord
  belongs_to :user
end

app/models/d3.rb
class D3 < ApplicationRecord
end

app/models/d3_contest.rb
class D3Contest < ApplicationRecord
  belongs_to :contest_type
  has_many :d3_results

  validates :name, presence: true, length: {maximum: 60, minimum: 5}
  validates :location, presence: true, length: {maximum: 60, minimum: 5}
  validates :date, presence: true
  validates :contest_type_id, presence: true


end

app/models/d3_result.rb
class D3Result < ApplicationRecord
  belongs_to :user
  belongs_to :d3_contest

  validates :d3_contest_id, presence: true
  validates :user_id, presence: true
  validates :rank, presence: true
  validates :swim, presence: true
  validates :t1, presence: true
  validates :bike, presence: true
  validates :t2, presence: true
  validates :run, presence: true
  validates :total, presence: true
end

app/models/licence.rb
class Licence < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/location.rb
class Location < ApplicationRecord
end

app/models/newsletter.rb
class Newsletter < ApplicationRecord
end

app/models/partner.rb
class Partner < ApplicationRecord
  belongs_to :user

  validates :user_id, presence: true
  validates :name, presence: true#, length {maximum: 40, minimum: 3}
  validates :contact, presence: true#, length {maximum: 60, minimum: 5}
  validates :offer, presence: true#, length {maximum: 100}
  validates :address, presence: true
  validates :description, presence: true
  mount_uploader :photo, PhotoUploader

  #TODO add picture and active:boolean
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  mount_uploader :photo, PhotoUploader

validates :title, presence: true, length: {maximum: 60, minimum: 5}
validates :link, presence: true #, format: {with: /\A(http.|https.|www.)/, message: "Ce n'est pas un site internet"}
validates :date, presence: true
validates :user_id, presence: true
# validates :photo, presence: true

def notification?
  !Notification.where(picture_id: self.id).empty?
end

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :size
  belongs_to :sport_type
  belongs_to :product_type

  mount_uploader :photo, PhotoUploader

  validates :name, presence: true, length: {maximum: 40, minimum: 5}
  validates :description, presence: true, length: {maximum: 550, minimum: 5}
  validates :price, presence: true
  # validates :stock, presence: true

  def notification?
    !Notification.where(product_id: self.id).empty?
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/size.rb
class Size < ApplicationRecord
  has_many :products
end

app/models/sport_type.rb
class SportType < ApplicationRecord
  has_many :products
end

app/models/test.rb
class Test < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
  mount_uploader :photo, PhotoUploader

  has_many :reviews
  has_many :likes
  has_many :authors
  has_many :articles, through: :authors
  has_many :participations
  has_many :notifications
  has_many :products


  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :mobil_phone, presence: true, numericality: true, length: {maximum: 13, minimum: 10 }

  def nb_articles(calculation_period)
    sum = 0
    # self.authors.each do |author|
    #   if author.article.updated_at > calculation_period
    #     sum += 1
    #   end
    # end
    self.articles.each do |article|
      if article.created_at > calculation_period
        if article.authors.first.user_id == self.id
          sum += 1
        end
      end
    end

    return sum
  end
end

app/models/week_day.rb
class WeekDay < ApplicationRecord
end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :location
  belongs_to :week_day
  belongs_to :sport_type
  belongs_to :licence
  validates :name, length: {maximum: 20}
  validates :location_id, presence: true
  validates :week_day_id, presence: true
  validates :sport_type_id, presence: true
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6">
      <p>Angoulême Triathlon</p>
      <p>Maison des Sports</p>
      <p>Rue des Mesniers </p>
      <p>Domaine de la Combe</p>
      <p>16710 Saint Yrieix sur Charente</p>

    </div>
    <div class="col-xs-12 col-sm-6">
      <a href="https://www.fftri.com/">
        FFTRI
      </a>
      <p>Réglementation</p>
      <p>AMA</p>
    </div>
  </div>
</div>

  <a href="https://www.instagram.com/jsa_triathlon_officiel/">
    <i class="fab fa-instagram"></i>
  </a>
  <a href="https://www.facebook.com/JSATriathlon/" target="_blank">
    <i class="fab fa-facebook-square"></i>
  </a>
  <a href="mailto:angoulemetriathlon@gmail.com?Subject=Demande de renseignements">
    <i class="fas fa-envelope"></i>
  </a>

</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->

  
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <a class="btn-navbar dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          Le club
        </a>
        <ul class="dropdown-menu">
          <li>
            <%= link_to "Le mot du président", clubs_path(anchor: 'le-mot-du-president'), class: "dropdown-item" %>
          </li>
          <li>
            <%= link_to "Les commissions", clubs_path(anchor: 'commissions'), class: "dropdown-item" %>
          </li>
          <li>
            <%= link_to "Les coachs", clubs_path(anchor: 'coachs'), class: "dropdown-item" %>
          </li>
          <li>
            <%= link_to "Les membres", clubs_path(anchor: 'les-membres'), class: "dropdown-item" %>
          </li>
        </ul>
      </div>
    </div>

    <%= link_to "Inscription", subscription_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <div class="navbar-wagon-item">
      <div class="dropdown">
        <a class="btn-navbar dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          Entraînements
        </a>
        <ul class="dropdown-menu">
          <li>
            <%= link_to "Planning", trainings_path(anchor: 'planning'), class: "dropdown-item" %>
          </li>
          <li>
            <%= link_to "Séances types", trainings_path(anchor: 'typical_session'), class: "dropdown-item" %>
          </li>
          <li>
            <%= link_to "Lien IDO", trainings_path(anchor: 'week_session'), class: "dropdown-item" %>
          </li>
        </ul>
      </div>
    </div>
    <%#= link_to "Planning", calendar_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%#= link_to "Entrainements", trainings_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%#= link_to "Tricross", tricross_path, class: "navbar-wagon-item navbar-wagon-link"  %>
    <%#= link_to "Evénements du club", club_events_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%#= link_to "Tenues", sportswears_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Résultats", results_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Les photos", pictures_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Divers", divers_path, class: "navbar-wagon-item navbar-wagon-link" %>


    <% if member? %>
      <%= link_to "Mes annonces", my_ads_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>

    <% if admin? %>
      <%= link_to "Mes articles", my_articles_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= render 'shared/notifications' %>
    <% end %>


    <% if user_signed_in? %>
      <!-- Links when logged in -->

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag helper_image_path(current_user), class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profil") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown hamburger-menu-size">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <% if user_signed_in? %>
        <div class="mobile-count-notifications">
          <%= helper_count_notifications %>
        </div>
      <% end %>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to clubs_path, class: "navbar-wagon-item navbar-wagon-link" do %>
            <i class="fa-solid fa-people-group"></i>
            Le club
          <% end %>
        </li>
        <li>
          <%= link_to subscription_path, class: "navbar-wagon-item navbar-wagon-link" do %>
            <i class="fa-solid fa-list-check"></i>
            Inscription
          <% end %>
        </li>
        <li>
          <%= link_to trainings_path, class: "navbar-wagon-item navbar-wagon-link" do %>
            <i class="fa-solid fa-fire"></i>
            Entrainements
          <% end %>
        </li>
        <% if user_signed_in? %>
          <li>
            <%= link_to notifications_path, class: "navbar-wagon-item navbar-wagon-link" do %>
              <i class="fas fa-bell"></i>
              Notifications
              (<%= helper_count_notifications %>)
            <% end %>
          </li>
          <li>
            <%= link_to my_articles_path, class: "navbar-wagon-item navbar-wagon-link" do %>
              <i class="far fa-newspaper"></i>
              Mes articles
            <% end %>
          </li>
          <li>
            <%= link_to edit_user_registration_path do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fas fa-sign-out-alt"></i>
              <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" do %>
              <i class="fas fa-sign-in-alt"></i>
              <%= t(".sign_in", default: "Login") %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_notifications.html.erb
<%= link_to notifications_path, class: "navbar-wagon-item navbar-wagon-link" do %>
  <div class="bell-content">
    <i class="fas fa-bell"></i>
    <div class="bell-quantity">
      <%= helper_count_notifications %>
    </div>
  </div>
<% end %>

app/views/shared/_taxe.html.erb
  <div class="taxes-shift" id="taxes-shift">
    <i class="fas fa-hands-helping"></i>
    Réduisez vos impôts en aidant le club
    <i class="fas fa-hands-helping"></i>
  </div>
  <div class="taxes" id="taxes">
    <div class="taxes-close">
    </div>
    <%= link_to impots_path do %>
      <div class="taxes-text">
        <i class="fas fa-hands-helping"></i>
        Réduisez vos impôts en aidant le club
        <i class="fas fa-hands-helping"></i>
      </div>
    <% end %>
    <div class="taxes-close" id="taxes-close">
      <i class="fas fa-times-circle"></i>
    </div>
  </div>

app/views/shared/_user_picture.html.erb
<div class="user-picture" style="background-image: url('<%= helper_user_picture(user) %>')">
  <div class="user-picture-name">
    <span>
      <%= user.firstname %>
      <%= user.lastname[0].upcase %>
    </span>
  </div>
</div>

app/views/shared/_visit_card.html.erb
<div class="col-xs-12 col-sm-4">
  <div class="visit-card">
    <div class="visit-card-name">
      <div><%= contact.firstname %></div>
      <div><%= contact.lastname %></div>
    </div>
    <!-- add role -->
    <div class="visit-card-photo">
      <img src="<%= helper_user_picture(contact) %>" alt="" class="visit-card-img">
    </div>
    <div class="visit-card-role">
      <i class="fas fa-user-tag"></i>
      <%= contact.profil %>
    </div>
    <div class="visit-card-mail">
      <i class="fas fa-envelope"></i>
      <a href="mailto:<%= contact.email %>" class=""><%= contact.email %></a>
    </div>
    <div class="visit-card-phone">
      <i class="fas fa-mobile-alt"></i>
      <a href="tel:<%= contact.mobil_phone %>" class=""><%= contact.mobil_phone.scan(/../).join("-")%></a>
    </div>
  </div>
</div>

app/views/shared/_workout_card.html.erb
<div class="workout-content box-shadow-md">
    <% if workout.sport_type_id == 2%>
        <div class="workout-title-content workout-color-swim">
    <% elsif workout.sport_type_id == 3 %>
        <div class="workout-title-content workout-color-run">
    <% else %>
        <div class="workout-title-content workout-color-bike">
    <% end %>
            <div class="workout-sport">
                <%= workout.sport_type.name %>
            </div>
            <div class="workout-sport-logo">
                <% if workout.sport_type_id == 2 %>
                    <i class="fas fa-swimmer fa-lg"></i>
                <% elsif workout.sport_type_id == 3 %>
                    <i class="fas fa-biking fa-lg"></i>
                <% elsif workout.sport_type_id == 4 %>
                    <i class="fas fa-running fa-lg"></i>
                <% else %>

                <% end %>
            </div>
            <div class="workout-hours-logo">
                <i class="fa-solid fa-clock"></i>
            </div>
            <div class="workout-hours">
                <%= l workout.start_hour, format:'%H:%M' %> > <%=l workout.end_hour, format: '%H:%M' %>
            </div>
        </div>
    <div class="workout-text">
        <%= workout.licence.name %>
        <%= workout.name %>
    </div>
    <div class="workout-location-logo">
        <i class="fa-solid fa-location-dot"></i>
    </div>
    <div class="workout-location">
        <%= workout.location.name %>
    </div> 
    <% if admin? %>
        <%= link_to edit_workout_path(workout) do %>
            <div class="workout-pen">
                <div>
                    <i class="fa-solid fa-pencil"></i>
                </div>
            </div>
        <% end %>
    <% end %>
</div>