config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'
  get 'calendar', to: 'pages#calendar'
  get 'club_events', to: 'pages#club_events'
  get 'trainings', to: 'pages#trainings'
  get 'contests', to: 'pages#contests'
  get 'school', to: 'pages#school'
  get 'results', to: 'pages#results'
  get 'my_articles', to: 'pages#my_articles'
  get 'my_ads', to: 'pages#my_ads'
  get 'triathlon2023', to: 'pages#triathlon2023'
  get 'forum_sports', to:'pages#forum_sports'
  get 'divers', to: 'pages#divers'
  get 'subscription', to: 'pages#subscription'

  get 'sportswears', to: 'products#sportswears'
  get 'petites_annonces', to: 'products#petites_annonces'

  get 'finances', to: 'clubs#finances'
  get 'impots', to: 'clubs#impots'
  get 'la_division_3', to: 'd3_contests#division_3'

  # Google API test
  get '/redirect', to: 'calendar#redirect', as: 'redirect'
  get '/callback', to: 'calendar#callback', as: 'callback'
  get '/calendars', to: 'calendar#calendars', as: 'calendars'
  get '/events', to: 'calendar#events', as: 'events'



  resources :pictures, only: [:index, :new, :create, :show, :edit, :update]
  #TODO create update method

  resources :users
  resources :dashboards, only: [:index]
  resources :articles do
    resources :reviews, only: [:new, :create]
    resources :likes, only: [:new, :create, :update]
    resources :participations, only: [:new, :create, :destroy]
  end
  resources :products, only: [:new, :show, :create, :edit, :update, :destroy]
  resources :clubs, only: [:index, :new, :edit, :show, :create, :update]
  resources :tests, only: [:index, :new, :create]
  resources :notifications, only: [:index, :edit, :update]
  resources :newsletters, only: [:index, :edit, :update]

  resources :d3_contests
  resources :d3_results
  resources :partners
  resources :workouts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.member } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/article.rb
class Article < ApplicationRecord
  # belongs_to :user
  belongs_to :article_type
  has_many :reviews
  has_many :likes
  has_many :participations
  has_many :authors
  mount_uploader :photo, PhotoUploader

  validates :name, presence: true, length: {maximum: 60, minimum: 5}
  validates :date, presence: true
  validates :article_type_id, presence: true
  validates :photo, presence: true
  validates :location, presence: true, length: {maximum: 60, minimum: 5}


  def total_likes
    sum = 0
    self.likes.each do |like|
      sum += like.like
    end
    return sum
  end

  def count_reviews
    sum = 0
    self.reviews.each do |review|
      if !review.content.nil?
        sum += 1
      end
    end
    return sum
  end

  def notification?
    !Notification.where(article_id: self.id).empty?
  end
end

app/models/article_type.rb
class ArticleType < ApplicationRecord
  has_many :articles
end

app/models/author.rb
class Author < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/club.rb
class Club < ApplicationRecord
  belongs_to :user
end

app/models/d3.rb
class D3 < ApplicationRecord
end

app/models/d3_contest.rb
class D3Contest < ApplicationRecord
  belongs_to :contest_type
  has_many :d3_results

  validates :name, presence: true, length: {maximum: 60, minimum: 5}
  validates :location, presence: true, length: {maximum: 60, minimum: 5}
  validates :date, presence: true
  validates :contest_type_id, presence: true


end

app/models/d3_result.rb
class D3Result < ApplicationRecord
  belongs_to :user
  belongs_to :d3_contest

  validates :d3_contest_id, presence: true
  validates :user_id, presence: true
  validates :rank, presence: true
  validates :swim, presence: true
  validates :t1, presence: true
  validates :bike, presence: true
  validates :t2, presence: true
  validates :run, presence: true
  validates :total, presence: true
end

app/models/licence.rb
class Licence < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/location.rb
class Location < ApplicationRecord
end

app/models/newsletter.rb
class Newsletter < ApplicationRecord
end

app/models/partner.rb
class Partner < ApplicationRecord
  belongs_to :user

  validates :user_id, presence: true
  validates :name, presence: true#, length {maximum: 40, minimum: 3}
  validates :contact, presence: true#, length {maximum: 60, minimum: 5}
  validates :offer, presence: true#, length {maximum: 100}
  validates :address, presence: true
  validates :description, presence: true
  mount_uploader :photo, PhotoUploader

  #TODO add picture and active:boolean
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  mount_uploader :photo, PhotoUploader

validates :title, presence: true, length: {maximum: 60, minimum: 5}
validates :link, presence: true #, format: {with: /\A(http.|https.|www.)/, message: "Ce n'est pas un site internet"}
validates :date, presence: true
validates :user_id, presence: true
# validates :photo, presence: true

def notification?
  !Notification.where(picture_id: self.id).empty?
end

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :size
  belongs_to :sport_type
  belongs_to :product_type

  mount_uploader :photo, PhotoUploader

  validates :name, presence: true, length: {maximum: 40, minimum: 5}
  validates :description, presence: true, length: {maximum: 550, minimum: 5}
  validates :price, presence: true
  # validates :stock, presence: true

  def notification?
    !Notification.where(product_id: self.id).empty?
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/size.rb
class Size < ApplicationRecord
  has_many :products
end

app/models/sport_type.rb
class SportType < ApplicationRecord
  has_many :products
end

app/models/test.rb
class Test < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
  mount_uploader :photo, PhotoUploader

  has_many :reviews
  has_many :likes
  has_many :authors
  has_many :articles, through: :authors
  has_many :participations
  has_many :notifications
  has_many :products


  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :mobil_phone, presence: true, numericality: true, length: {maximum: 13, minimum: 10 }

  def nb_articles(calculation_period)
    sum = 0
    # self.authors.each do |author|
    #   if author.article.updated_at > calculation_period
    #     sum += 1
    #   end
    # end
    self.articles.each do |article|
      if article.created_at > calculation_period
        if article.authors.first.user_id == self.id
          sum += 1
        end
      end
    end

    return sum
  end
end

app/models/week_day.rb
class WeekDay < ApplicationRecord
end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :location
  belongs_to :week_day
  belongs_to :sport_type
  belongs_to :licence
  validates :name, length: {maximum: 20}
  validates :location_id, presence: true
  validates :week_day_id, presence: true
  validates :sport_type_id, presence: true
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  before_action :find_picture, only: [:edit, :update]
#TODO remove :new
  def index
    @pictures = Picture.all
                        .sort_by {|picture| picture.date}
                        .reverse
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.new(picture_params)
    if @picture.save
      create_notifications(@picture.id, 'picture')
      redirect_to pictures_path
    else
      render :new
    end
  end

  def update
    @picture.update(picture_params)
    if @picture.save
      if @picture.notification?
        update_notifications(@picture.id, 'picture')
      else
        create_notifications(@picture.id, 'picture')
      end
      redirect_to pictures_path
    else
      render :edit
    end
  end

private
  def picture_params
    params.require(:picture).permit(
      :link,
      :title,
      :user_id,
      :date,
      :like,
      :photo)
  end

  def find_picture
    @picture = Picture.find(params[:id])
  end

end

app/views/pictures/_form_picture.html.erb
<%= simple_form_for(@picture) do |f| %>
  <%= f.error_notification %>
  <%= f.input :title, label: 'Titre' %>
  <div class="datepicker">
    <%= f.input :date, as: :date, order: [:day, :month, :year], input_html: {class: 'date-time'} %>
  </div>
  <%= f.input :link, label: "Colle ici le lien vers l'album photo" %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <div class="article-form-photo">
    <% if @picture.photo? %>
      <%= cl_image_tag(@picture.photo, width: 400) %>
    <% end %>
  </div>
  <%= f.submit "Créer l'album", class: 'btn btn-danger btn-block' %>
<% end %>

app/views/pictures/edit.html.erb
<div class="container">
  <div class="row">
    <h3>Modifier l'album photo</h3>
    <%= render 'form_picture' %>
  </div>
</div>

app/views/pictures/index.html.erb
<div class="container">
<h3>Albums photos</h3>
  <div class="row">
    <% @pictures.each do |picture| %>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <a href="<%= picture.link %>" target="_blank">
          <div class="picture-card">
            <div class="picture-card-photo picture" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url('<%= helper_image_path(picture) %>');">
              <div class="picture-card-title">
                <%= picture.title %>
              </div>
              <div class="picture-card-name">
                <%= render 'shared/user_picture', user: picture.user %>
              </div>
              <div class="picture-card-date">
                <%= picture.date.strftime('%d/%m/%Y') %>
              </div>
            </div>
            <div class="picture-card-container">
              <div class="picture-card-like">
              </div>
              <div class="picture-card-review">
              </div>
            </div>
            <% if admin? %>
              <%= link_to edit_picture_path(picture) do %>
                <div class="article-edit-link ">
                  <i class="far fa-edit"></i>
                </div>
              <% end %>
            <% end %>
          </div>
        </a>
      </div>
    <% end %>
  </div>
  <% if member? %>
    <%= link_to new_picture_path do %>
      <div class="hidden-sm hidden-md hidden-lg">
        <%= link_to new_picture_path do %>
          <div class="plus-button plus-button-mobile">
            <i class="fas fa-camera-retro"></i>
          </div>
        <% end %>
      </div>
      <div class="hidden-xs">
        <%= link_to new_picture_path do %>
          <div class="plus-button plus-button-desktop">
            <i class="fas fa-camera-retro"></i>
              <div> Ajouter un album photo</div>
          </div>
        <% end %>
      </div>

    <% end %>
  <% end %>
</div>

app/views/pictures/new.html.erb
<div class="container">
  <div class="row">
    <h3>Ajouter un album photo</h3>
    <%= simple_form_for(@picture) do |f| %>
    <%= f.error_notification %>
      <%= f.input :title, label: 'Titre' %>
      <div class="datepicker">
        <%= f.input :date, as: :date, order: [:day, :month, :year], input_html: {class: 'date-time'} %>
      </div>
      <%= f.input :link, label: "Colle ici le lien vers l'album photo" %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.input :photo %>
      <%= f.input :photo_cache, as: :hidden %>
      <%= f.submit "Créer l'album", class: 'btn btn-danger btn-block' %>
    <% end %>
  </div>
</div>