config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'
  get 'calendar', to: 'pages#calendar'
  get 'club_events', to: 'pages#club_events'
  get 'trainings', to: 'pages#trainings'
  get 'contests', to: 'pages#contests'
  get 'school', to: 'pages#school'
  get 'results', to: 'pages#results'
  get 'my_articles', to: 'pages#my_articles'
  get 'my_ads', to: 'pages#my_ads'
  get 'triathlon2023', to: 'pages#triathlon2023'
  get 'forum_sports', to:'pages#forum_sports'
  get 'divers', to: 'pages#divers'
  get 'subscription', to: 'pages#subscription'

  get 'sportswears', to: 'products#sportswears'
  get 'petites_annonces', to: 'products#petites_annonces'

  get 'finances', to: 'clubs#finances'
  get 'impots', to: 'clubs#impots'
  get 'la_division_3', to: 'd3_contests#division_3'

  # Google API test
  get '/redirect', to: 'calendar#redirect', as: 'redirect'
  get '/callback', to: 'calendar#callback', as: 'callback'
  get '/calendars', to: 'calendar#calendars', as: 'calendars'
  get '/events', to: 'calendar#events', as: 'events'



  resources :pictures, only: [:index, :new, :create, :show, :edit, :update]
  #TODO create update method

  resources :users
  resources :dashboards, only: [:index]
  resources :articles do
    resources :reviews, only: [:new, :create]
    resources :likes, only: [:new, :create, :update]
    resources :participations, only: [:new, :create, :destroy]
  end
  resources :products, only: [:new, :show, :create, :edit, :update, :destroy]
  resources :clubs, only: [:index, :new, :edit, :show, :create, :update]
  resources :tests, only: [:index, :new, :create]
  resources :notifications, only: [:index, :edit, :update]
  resources :newsletters, only: [:index, :edit, :update]

  resources :d3_contests
  resources :d3_results
  resources :partners
  resources :workouts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.member } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :size
  belongs_to :sport_type
  belongs_to :product_type

  mount_uploader :photo, PhotoUploader

  validates :name, presence: true, length: {maximum: 40, minimum: 5}
  validates :description, presence: true, length: {maximum: 550, minimum: 5}
  validates :price, presence: true
  # validates :stock, presence: true

  def notification?
    !Notification.where(product_id: self.id).empty?
  end
end

app/models/product_type.rb
class ProductType < ApplicationRecord
  has_many :products
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:sportswears, :show, :petites_annonces]
  before_action :load_collections, only: [:new, :create, :edit, :update]
  before_action :find_product, only: [:show, :edit, :update, :destroy]
  before_action :mailing_list_1, only: [:create, :update]
  before_action :mailing_list_2, only: [:create, :update]
  before_action :mailing_list_3, only: [:create, :update]

  def sportswears
    @sportswears = if user_signed_in? && current_user.role == 'admin'
                    Product.where(product_type_id: 1)
                          .sort_by {|product| product.sport_type}
                  else
                    Product.where(product_type_id: 1)
                          .where(active: true)
                          .sort_by {|product| product.sport_type}
                  end
  end

  def petites_annonces
    @triathlon_products = select_product(1)
    @swim_products = select_product(2)
    @bike_products = select_product(3)
    @run_products = select_product(4)
    @electro_products = select_product(5)
    @rent_products = select_product(6)

    @sold_products = Product.where(product_type_id: 2)
                              .where(active: true)
                              .where(sold: true)
                              .where("updated_at > ?", Time.now-30.day)

  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      if @product.product_type_id == 2
        AdMailer.new_ad(@product, @list_members_1).deliver_later
        AdMailer.new_ad(@product, @list_members_2).deliver_later
        AdMailer.new_ad(@product, @list_members_3).deliver_later
      end
      create_notifications(@product.id, 'product')
      redirect_to product_path(@product)
    else
      render :new
    end

  end

  def edit
  end

  def update
    @product.update(product_params)
    if @product.save
      if @product.notification?
        update_notifications(@product.id, 'product')
      else
        create_notifications(@product.id, 'product')
      end
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    @product.destroy
    redirect_to sportswears_path
  end

private
  def product_params
    params.require(:product).permit(
      :user_id,
      :name,
      :description,
      :price,
      :stock,
      :size_id,
      :sex,
      :sport_type_id,
      :product_type_id,
      :active,
      :sold,
      :photo)
  end

  def find_product
    @product = Product.find(params[:id])
  end

  def load_collections
    @sizes = Size.all
    @product_types = ProductType.all
    @sex = ['Homme', 'Femme', 'Unisex']
    @sport_types = SportType.all
  end

  def select_product(sport_type_id)
    Product.where(product_type_id: 2)
           .where(sport_type_id: sport_type_id)
           .where(active: true)
           .where(sold: false)
           .sort_by {|product| product.sport_type}
  end

  def mailing_list_1
    @list_members_1 = User.where(notification: true)
                        .where(mailing_group: 1)
                        .map{|user| user.email}.join(';')
  end
  def mailing_list_2
    @list_members_2 = User.where(notification: true)
                        .where(mailing_group: 2)
                        .map{|user| user.email}.join(';')
  end
  def mailing_list_3
    @list_members_3 = User.where(notification: true)
                        .where(mailing_group: 3)
                        .map{|user| user.email}.join(';')
  end

end

app/views/products/_card_product.html.erb
<div class="card-product-content">
  <% if product.sold %>
    <div class="product-sold">
     😃🎉 VENDU 🎉😃
    </div>
  <% end %>
  <%= link_to product_path(product) do %>
    <div class="card-product-photo" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.1)), url('<%= helper_image_path(product) %>') " >
      <% if !product.active %>
        <div class="picture-card-status">
          <i class="fas fa-exclamation-triangle"></i>
          non publié
          <i class="fas fa-exclamation-triangle"></i>
        </div>
      <% end %>
      <div class="card-product-user">
        <%= render 'shared/user_picture', user: product.user %>
      </div>
    </div>
  <% end %>
  <div class="card-product-title">
    <h3 class="card-product-title-ellipsis"><%= product.name %></h3>
    <div>Taille : <%= product.size.name %> <%= product.sex %></div>
    <div><%= product.price %>€</div>

  </div>


  <% if member? %>
  <!-- TODO -->
    <%= link_to edit_product_path(product) do %>
      <div class="article-edit-link ">
        <i class="far fa-edit"></i>
      </div>
    <% end %>
  <% end %>

</div>

app/views/products/_card_sportswears.html.erb
<div class="card-sportswears-content">
  <%= link_to product_path(product) do %>
    <div class="card-sportswears-photo" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.1)), url('<%= helper_image_path(product) %>') " >
      <div class="card-status-content">
        <% if !product.active %>
          <div class="sportswears-status">
            <i class="fas fa-exclamation-triangle"></i>
            non publié
            <i class="fas fa-exclamation-triangle"></i>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
  <div class="card-sportswears-title">
    <div class="card-sportswears-title-ellipsis"><%= product.name %></div>
    <div class="card-sportswears-sport-type">
      <%= product.sport_type.name %>
    </div>
  </div>
  <% if member? %>
  <!-- TODO -->
    <%= link_to edit_product_path(product) do %>
      <div class="article-edit-link ">
        <i class="far fa-edit"></i>
      </div>
    <% end %>
  <% end %>
</div>
<div></div>

app/views/products/_form_product.html.erb
<%= simple_form_for(@product) do |f| %>
  <%= f.error_notification %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.input :photo, label: t('.photo') %>
  <%= f.input :photo_cache, as: :hidden %>
  <div class="article-form-photo">
    <% if @product.photo? %>
      <%= cl_image_tag(@product.photo, width: 400) %>
    <% end %>
  </div>
  <%= f.input :name, label: t('.name'), input_html: {maxlength: 40} %>
  <div class="counter-text counter-hide" id="counter-name">...</div>
  <%= f.text_area :description, class: 'ckeditor', label: t('.description'), input_html: {placeholder: t('.placeholder_description'), maxlength: 350} %>
  <div class="counter-text counter-hide" id="counter-description">...</div>
  <%= f.input :price, label: t('.price') %>
  <%= f.input :stock, collection: 1..20, label: t('.stock') %>
  <%= f.input :size_id, label: t('.size') ,collection: @sizes %>
  <%= f.input :sex, collection: @sex, label: t('.sex') %>
  <%= f.input :sport_type_id, label: t('.sport_type') , collection: @sport_types %>
  <% if admin? %>
    <div class="article-mail-div">
      <div class="administrator-content">
        <div class="product-type-content">
          <%= f.input :product_type_id, label: t('.product_type'), collection: @product_types%>
        </div>
      </div>

    </div>
  <% else %>
    <%= f.input :product_type_id, input_html: {value: 2}, as: :hidden%>
  <% end %>
  <div class="product-form-checkbox">
    <%= f.input :active, label: t('.active') %>
    <%= f.input :sold, label: t('.sold') %>
  </div>
  <%= f.submit t('.submit') , class: 'btn btn-danger btn-block' %>

<% end %>

app/views/products/_go_top.html.erb
<div class="go-top">
  <a href="#go-top">
    <i class="far fa-arrow-alt-circle-up"></i>
  </a>
</div>

app/views/products/_gray_triangle.html.erb
<div class="rectangles-content">
  <div class="gray-rectangle">
  </div>
  <div class="white-left-triangle">
  </div>
</div>

app/views/products/_red_triangle.html.erb
<div class="rectangles-content">
  <div class="red-rectangle">
  </div>
  <div class="white-right-triangle">
  </div>
</div>

app/views/products/bourse_echange.html.erb
<div class="container">
  <div class="row">
    <h3>Bourse d'échange</h3>
    <% @products.each do |product| %>
      <div class="col-xs-12 col-sm-6">
        <%= render 'card_product', product: product %>
      </div>
    <% end %>
    <% if member? %>
      <%= link_to new_product_path do %>
        <div class="plus-button">
          <i class="far fa-edit"></i>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/products/edit.html.erb
<div class="container">
  <div class="row">
    <h3>Modification du produit</h3>
    <%= render 'form_product' %>
  </div>
</div>

app/views/products/new.html.erb
<div class="container">
  <div class="row">
    <h3>Déposer une annonce</h3>
    <%= render 'form_product' %>
  </div>
</div>

app/views/products/petites_annonces.html.erb
<div class="container">
  <div class="row">
    <div class="product-heading-content">
      <div class="product-heading-title" id="go-top">
        Petites annonces
      </div>
    </div>
    <div class="hidden-xs">
      <div class="a-list-content">
        <% if @triathlon_products.count > 0 %>
          <a href="#triathlon" class="product-a-list">Triathlon (<%= @triathlon_products.count %>)</a>
        <% end %>
        <% if @swim_products.count > 0 %>
          <a href="#swim" class="product-a-list">Natation (<%= @swim_products.count %>)</a>
        <% end %>
        <% if @bike_products.count > 0 %>
          <a href="#bike" class="product-a-list">Vélo (<%= @bike_products.count %>)</a>
        <% end %>
        <% if @run_products.count > 0 %>
          <a href="#run" class="product-a-list">Course à pied (<%= @run_products.count %>)</a>
        <% end %>
        <% if @electro_products.count > 0 %>
          <a href="#electro" class="product-a-list">Electro (<%= @electro_products.count %>)</a>
        <% end %>
        <% if @rent_products.count > 0 %>
          <a href="#rent" class="product-a-list">Location (<%= @rent_products.count %>)</a>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div id="triathlon">
  <% if @triathlon_products.count > 0 %>
    <%= render 'gray_triangle' %>
    <div class="container">
      <div class="row">
        <div class="product-heading-content">
          <div class="product-heading-title">
            Triathlon
          </div>
          <%= render 'go_top' %>
        </div>
        <% @triathlon_products.each do |product| %>
          <div class="col-xs-12 col-sm-6 col-md-4">
            <%= render 'card_product', product: product %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div id="swim">
  <% if @swim_products.count > 0 %>
    <%= render 'red_triangle' %>
    <div class="container">
      <div class="row">
        <div class="product-heading-content">
          <div class="product-heading-title">
            Natation
          </div>
          <%= render 'go_top' %>
        </div>
        <% @swim_products.each do |product| %>
          <div class="col-xs-12 col-sm-6 col-md-4">
            <%= render 'card_product', product: product %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div id="bike">
  <% if @bike_products.count > 0 %>
    <%= render 'gray_triangle' %>
    <div class="container">
      <div class="row">
        <div class="product-heading-content">
          <div class="product-heading-title">
            Vélo
          </div>
          <%= render 'go_top' %>
        </div>
         <% @bike_products.each do |product| %>
          <div class="col-xs-12 col-sm-6 col-md-4">
            <%= render 'card_product', product: product %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div id="run">
  <% if @run_products.count > 0 %>
    <%= render 'red_triangle' %>
    <div class="container">
      <div class="row">
        <div class="product-heading-content">
          <div class="product-heading-title">
            Course à pied
          </div>
          <%= render 'go_top' %>
        </div>
          <% @run_products.each do |product| %>
            <div class="col-xs-12 col-sm-6 col-md-4">
              <%= render 'card_product', product: product %>
            </div>
          <% end %>
      </div>
    </div>
  <% end %>
</div>
<div id="electro">
  <% if @electro_products.count > 0 %>
    <%= render 'gray_triangle' %>
    <div class="container">
      <div class="row">
        <div class="product-heading-content">
          <div class="product-heading-title">
            Electro
          </div>
          <%= render 'go_top' %>
        </div>
        <% @electro_products.each do |product| %>
          <div class="col-xs-12 col-sm-6 col-md-4">
            <%= render 'card_product', product: product %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div id="rent">
  <% if @rent_products.count > 0 %>
    <%= render 'red_triangle' %>
    <div class="container">
      <div class="row">
        <div class="product-heading-content">
          <div class="product-heading-title">
            Location
          </div>
          <%= render 'go_top' %>
        </div>
        <% @rent_products.each do |product| %>
          <div class="col-xs-12 col-sm-6 col-md-4">
            <%= render 'card_product', product: product %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div>
  <% if @sold_products.count > 0 %>
    <%= render 'gray_triangle' %>
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <div class="product-heading-content">
            <div class="product-heading-title">
              Vendus
            </div>
            <%= render 'go_top' %>
          </div>
          <% @sold_products.each do |product| %>
            <div class="col-xs-12 col-sm-6 col-md-4">
              <%= render 'card_product', product: product %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

  <% end %>
</div>

<% if member? %>
  <div class="hidden-sm hidden-md hidden-lg">
    <%= link_to new_product_path do %>
      <div class="plus-button plus-button-mobile">
        <i class="far fa-edit"></i>
      </div>
    <% end %>
  </div>
  <div class="hidden-xs">
    <%= link_to new_product_path do %>
      <div class="plus-button plus-button-desktop">
        <i class="far fa-edit"></i>
         Déposer une annonce
      </div>
    <% end %>
  </div>
<% end %>

app/views/products/show.html.erb
<div class="product-show-content">
  <div class="return-link">
    <% if @product.product_type_id == 2 %>
      <%= link_to petites_annonces_path do %>
        <i class="fas fa-long-arrow-alt-left"></i> retour vers les annonces
      <% end %>
    <% else %>
    <%= link_to sportswears_path do %>
        <i class="fas fa-long-arrow-alt-left"></i> retour vers les tenues
      <% end %>

    <% end %>
  </div>
  <div class="product-show-triangle"></div>
  <div class="product-show-title">
    <%= @product.name.upcase %>
  </div>
  <div class="product-show-sporttype">
    <%= @product.sport_type.name %>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6">
        <%= link_to product_path(@product) do %>
          <div class="card-product-photo" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.1)), url('<%= helper_image_path(@product) %>') " >
            <% if !@product.active %>
              <div class="picture-card-status">
                <i class="fas fa-exclamation-triangle"></i>
                non publié
                <i class="fas fa-exclamation-triangle"></i>
              </div>
            <% end %>
            <div class="product-show-user">
              <%= render 'shared/user_picture', user: @product.user %>
            </div>
            <% if @product.sold %>
              <div class="product-show-sold">
               😃🎉 VENDU 🎉😃
              </div>
            <% end %>
            <% if member? %>
              <%= link_to edit_product_path(@product) do %>
                <div class="article-edit-link ">
                  <i class="far fa-edit"></i>
                </div>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="col-xs-12 col-sm-6">
        <div class="product-show-information-content">
          <div class="product-show-information">
            <div class="product-show-price">
              <%= @product.price %>€
            </div>
            <% if @product.product_type_id == 1 %>
              <div class="product-show-stock">
                Stock : <%= @product.stock %>
              </div>
            <% else %>
              <div class="product-show-size">
                Taille : <%= @product.size.name %>
              </div>
            <% end %>
            <div>
              <%= @product.sex %>
            </div>
          </div>
          <div class="product-show-description">
            <%= raw @product.description %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<% if @product.product_type.id == 2 %>
  <div class="product-show-seller">
      <div class="product-show-seller-information">
        <div>
          Contactez
          <%= @product.user.firstname %>
          <%= @product.user.lastname %>
          <i class="fas fa-long-arrow-alt-right"></i>
        </div>

        <div>
          <i class="fas fa-mobile-alt"></i>
          <a href="tel: <%= @product.user.mobil_phone %>", class="phone-link">
            <%= @product.user.mobil_phone %>
          </a>
        </div>
        <div>
          <i class="far fa-envelope"></i>
          <a href="mailto:<%= @product.user.email %>">
            <%= @product.user.email %>
          </a>
        </div>
      </div>
  </div>
<% end %>

app/views/products/sportswears.html.erb
<div class="sportswears-content">
  <div class="sportswears-triangle">

  </div>
  <div class="sportswears-triangle-white">

  </div>
  <div class="container">
    <div class="row">
      <div class="sportswears-title-content">
        <div class="sportswears-title">
          Les tenues du club
        </div>
      </div>
      <div class="sportswears-form-content gradient-an-blue-purple">
        <a href="https://docs.google.com/forms/d/e/1FAIpQLScY75oSDXVk4Nh5w9Werc9SZ5RwwjO-2NhsQnwcEnTadh_zqg/viewform?usp=sf_link" target="_blank">
          <div class="sportswears-form animated infinite flash slower">
            Cliquez-ici pour commander vos tenues
          </div>
        </a>
      </div>
      <% @sportswears.each do |sportswear| %>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
          <%= render 'card_sportswears', product: sportswear %>
        </div>
      <% end %>
      <% if admin? %>
        <%= link_to new_product_path do %>
          <div class="hidden-sm hidden-md hidden-lg">
            <%= link_to new_product_path do %>
              <div class="plus-button plus-button-mobile">
                <i class="far fa-edit"></i>
              </div>
            <% end %>
          </div>
          <div class="hidden-xs">
            <%= link_to new_product_path do %>
              <div class="plus-button plus-button-desktop">
                <i class="far fa-edit"></i>
                 Créer une nouvelle tenue
              </div>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>